---
title: "crypto"
author: "Alex"
date: "5/27/2021"
output: html_document 
---
## https://www.kaggle.com/sudalairajkumar/cryptocurrencypricehistory
NOTE: THIS DOES NOT CONSTITUTE INVESTMENT ADVICE
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(zoo)
library(lubridate)
coins = read_csv('./aggreg_coins.csv') #loading in original dataset
head(coins) #inspecting 
coins = na.omit(coins) #getting rid of the n/a's (there weren't many)
coins$date_time = as.Date(coins$Date) #converting over the timestamp to just date
coins$weekday = weekdays.Date(coins$date_time) #getting a new column with the weekday
require(Hmisc)
coins$d_i_m=monthDays(as.Date(coins$date_time)) #getting the day of the month
coins %>% group_by(Name, date_time) %>% summarise (open = Open, close = Close)
coins
post = coins #[coins$date_time>'2015-12-31',] Setting to a new df that i can keep working on 
post$day_in_mo = substr(post$date_time,9,10) #extracting just the day of month in a new column
post$perc_in_mo_bod = (as.numeric(post$day_in_mo )-1) / as.numeric(post$d_i_m )
post
#getting the percent in to the total of a given month, in percent, for the beginning of the day
post$perc_in_mo_eod = as.numeric(post$day_in_mo)  / as.numeric(post$d_i_m)
post
#getting the percent in to the total of a given month, in percent, for the end of the day
#rollmean{zoo}
```
```{r}
cal <- read_csv('./calendar.csv')
cal$date = as.Date(cal$date)
cal
#dropping in external data csv that i made
```



```{r}
wip <- post #assigninng to a new df that i continue to work on
library(scales)
wip$day_ret = (wip$Close / wip$Open)-1 #getting the returns on a percent basis, by day to normalise across all crypto's

wip$date_time
cal$date

full_df <- merge(wip,cal,by.x='date_time',by.y='date') #merging calendar info into a new full dataframe
full_df %>% ungroup %>% arrange(desc('date_time'),'Name') #sorting the new full data frame
sorted_df = arrange(full_df, Name, date_time ,by_group=F) #sub sorting
sorted_df #inspecting
sorted_df$mo_yr = paste0(substr(sorted_df$date_time,6,7),"-",substr(sorted_df$date_time,1,4)) #dropping in the month-year 
sorted_df

weekly_ret = group_by(sorted_df, Name, wk_num) %>% summarise(wk_ret_mean=mean(day_ret),wk_ret_sd=sd(day_ret))
weekly_ret #summary of the weekly returns, aggregated by coin and week number, means and standard dev's 
```

```{r}
sorted_df
monthly_ret = group_by(sorted_df, Name, mo_yr) %>% summarise(mo_ret_mean=mean(day_ret),mo_ret_sd=sd(day_ret)) #doing a similar summary on the monthly level, has concatenated month-year
monthly_ret

```
```{r}
sorted_df$yr = substr(sorted_df$date_time,1,4) #getting a year column on its own
sorted_df$mo = substr(sorted_df$date_time,6,7)#getting month on its own


sorted_df$qtr_yr = paste(ifelse(sorted_df$mo %in% c('01','02','03'), '01', ifelse(sorted_df$mo %in% c('04','05','06'), '02',ifelse(sorted_df$mo %in% c('07','08','09'), '03','04'))),'-',sorted_df$yr) #creating a column for the quarter based on the month number 

gsub(' ','',sorted_df$qtr_yr) #getting rid of whitespace in the qtr column

sorted_df
yearly_ret = group_by(sorted_df, Name, yr) %>% summarise(yr_ret_mean=mean(day_ret),yr_ret_sd=sd(day_ret)) #making a yearly summary table
yearly_ret

qtrly_ret = group_by(sorted_df, Name, qtr_yr) %>% summarise(qtr_ret_mean=mean(day_ret),qtr_ret_sd=sd(day_ret)) #Quarterly summary dataframe 
qtrly_ret

```
```{r}
all_cols = sorted_df
all_cols

sorted_df

weekly_ret
sorted_df = left_join(sorted_df, weekly_ret, by=c('Name' = 'Name', 'wk_num' = 'wk_num'))


monthly_ret
sorted_df = left_join(sorted_df, monthly_ret, by=c('Name' = 'Name', 'mo_yr' = 'mo_yr'))


qtrly_ret
sorted_df = left_join(sorted_df,qtrly_ret, by = c('Name' ='Name' , 'qtr_yr' = 'qtr_yr'))

yearly_ret
sorted_df = left_join(sorted_df,yearly_ret, by = c('Name' ='Name' , 'yr' = 'yr'))
##Getting the Summary info by week, month, qtr, and year into the main dataframee

sorted_df
```

```{r}
norm_df = sorted_df
norm_df
```
```{r}
#Aggregating for the day of week regardless of the week, summary
norm_df
day_tbl = norm_df %>% group_by(Name, wk_day_n) %>% summarise(day_of_wk_ret =mean(day_ret))
day_tbl
#Getting the associated min and max days, for table output in shiny
dow_max = day_tbl %>% group_by(Name) %>% summarise(max_dow = max(day_of_wk_ret))
dow_max
dow_min = day_tbl %>% group_by(Name) %>% summarise(min_dow = min(day_of_wk_ret))
dow_min
agg_max_min = left_join(day_tbl,dow_max, left_on ='Name',right_on='Name')
agg_max_min
agg_max_min = left_join(agg_max_min,dow_min, left_on ='Name',right_on='Name')

agg_max_min$max_day = agg_max_min$max_dow == agg_max_min$day_of_wk_ret
agg_max_min$min_day = agg_max_min$min_dow == agg_max_min$day_of_wk_ret

final_max_min = agg_max_min %>% dplyr::select(Name, wk_day_n, day_of_wk_ret, max_dow, max_day, min_dow, min_day) %>% filter(min_day==T | max_day==T)
fin_day = final_max_min %>% dplyr::select(Name, wk_day_n, day_of_wk_ret, max_day, min_day)
fin_day
```

```{r}
# library(reshape2)
#All coins, aggregated by day of wk
all_Names_daily <- ggplot(day_tbl, aes(x=wk_day_n, y=day_of_wk_ret, col=Name)) + geom_line()+xlab('Weekday (1=Sunday...)')+ylab('Daily Mean of Returns')+ggtitle('Daily Mean of Returns by Coin')
all_Names_daily
# melted %>% group_by(Name) %>% top_n(1,value)
day_tbl
ttl_by_day = day_tbl %>% group_by(wk_day_n) %>% summarise(agg_daily_return = mean(day_of_wk_ret, na.rm=T))
ttl_by_day
agg_daily <- ggplot(ttl_by_day, aes(x=wk_day_n, y=agg_daily_return)) +geom_line()+xlab('Weekday Num. (1=Sunday...)')+ylab('Aggregate Crypto Return by Day')+ggtitle('Returns by Day of Wk, All Coins Agg.')
#Graph of all of the coins aggregated by day of wk
agg_daily

```


```{r}
#Doing the same graph summary, by month this time. By coin and then at the aggregate, with a table output for Shiny
norm_df
mo_tbl = norm_df %>% group_by(Name, mo, day_in_mo) %>% summarise(mo_ret_mean=mean(day_ret))
mo_tbl
monthly_tbl <- mo_tbl %>% group_by(Name, day_in_mo) %>% summarise(mo_ret_mean = mean(mo_ret_mean))
monthly_coin = mo_tbl %>% group_by(Name, mo, day_in_mo) %>% summarise(month_avg_return = mean(mo_ret_mean))
monthly_coin

m  = norm_df %>% group_by(Name, mo, day_in_mo) %>% summarise(mo_ret_mean=mean(day_ret))
m1 <- m %>% group_by(Name, mo) %>% summarise(max = max(mo_ret_mean), min = min(mo_ret_mean))
m2 <- left_join(monthly_coin , m1, left_on=c(Name, mo), right_on=c(Name, mo))
m2$max_day = m2$month_avg_return==m2$max
m2$min_day = m2$month_avg_return==m2$min
m2
max_tbl = filter(m2, max_day==T)
min_tbl = filter(m2, min_day==T)
max_tbl
min_tbl
```

```{r}
#Max and min days at the month level, by coin, for table output for Shiny
monthly_max = monthly_tbl %>% group_by(Name)%>% summarise(max=max(mo_ret_mean))
monthly_max
monthly_min = monthly_tbl %>% group_by(Name)%>% summarise(min=min(mo_ret_mean))
monthly_min

mo_max_min = left_join(monthly_tbl, monthly_max, on='Name')
mo_max_min = left_join(mo_max_min, monthly_min, on='Name')
mo_max_min$max_day = mo_max_min$max == mo_max_min$mo_ret_mean
mo_max_min$min_day = mo_max_min$min == mo_max_min$mo_ret_mean
mo_max_min

final_mo = mo_max_min %>% dplyr::select(Name, day_in_mo, mo_ret_mean, max_day, min_day) %>% filter(max_day==T | min_day==T)
final_mo

```

```{r}
#na.omit(norm_mo_tbl)
# library(reshape2)

monthly_tbl
all_Names_monthly <- ggplot(mo_tbl,aes(x=day_in_mo, y=mo_ret_mean, group=Name)) + geom_line(aes(colour=Name))+xlab("Day / Month")+ylab('Daily Return Percent')+ggtitle('Daily Returns by Coin by Month')
all_Names_monthly + facet_wrap(~mo)

```
```{r}
# melted_mo %>% group_by(Name) %>% top_n(1,value)

#Doing the same week functions to the month--by coin and then aggregated 
ttl_by_mo = mo_tbl %>% group_by(day_in_mo, mo) %>% summarise(agg_monthly_return = mean(mo_ret_mean, na.rm=T))
ttl_by_mo_by_day =mo_tbl %>% group_by(day_in_mo) %>% summarise(agg_monthly_return = mean(mo_ret_mean, na.rm=T))

agg_monthly <- ggplot(data = ttl_by_mo_by_day, aes(x=day_in_mo, y=agg_monthly_return)) +geom_line(aes(group = 1))+xlab('Day of Month')+ylab('Avg. Daily Return')+ggtitle('Average Daily Return by Day of Month, all Coins Agg.')
agg_monthly

```
```{r}
##Doing a lot of transformations for the date here--essentially i'm getting the first day of the quarter, depending on the quarter, and then figuring out what day the observation represents with respect to that quarter
norm_df$mo_day = substr(norm_df$date_time,6,10)
norm_df$first_qtr_day =paste(norm_df$yr,'-', ifelse(substr(norm_df$qtr_yr,1,2)=='01','01-01',ifelse(substr(norm_df$qtr_yr,1,2)=='02','04-01',ifelse(substr(norm_df$qtr_yr,1,2)=='03','07-01','10-01'))))
norm_df$first_qtr_day = gsub(" ", "",norm_df$first_qtr_day)
norm_df$qtr_yr = gsub(' ', '' , norm_df$qtr_yr)

as.Date(norm_df$first_qtr_day)
as.Date(norm_df$date_time)
norm_df$day_into_qtr = as.Date(norm_df$date_time) - as.Date(norm_df$first_qtr_day) +1
norm_df$qtr = substr(norm_df$qtr_yr,1,2)

qtr_tbl = norm_df %>% group_by(Name, qtr, day_into_qtr) %>% summarise(qtr_ret=mean(day_ret))

na.omit(qtr_tbl)
qtr_tbl
##And then doing the same functions to aggregate at the quarter level--summaries for each coin and then total level
quarterly_tbl = qtr_tbl %>% group_by(Name, day_into_qtr) %>% summarise (qtr_ret_mean = mean(qtr_ret))
quarterly_tbl
all_Names_quarterly <- ggplot(qtr_tbl,aes(x=day_into_qtr, y=qtr_ret, group=Name)) + geom_line(aes(colour=Name))

all_Names_quarterly + facet_grid(~qtr)+xlab('Quarter/Day')+ylab('Daily Return')+ggtitle('Daily Returns by Day by Coin')
# melted_qtr %>% group_by(Name) %>% top_n(1,value)

ttl_by_qtr = qtr_tbl %>% group_by(qtr, day_into_qtr) %>% summarise(agg_quarterly_return = mean(qtr_ret, na.rm=T))
ttl_by_qtr
agg_qtrly <- ggplot(data = ttl_by_qtr, aes(x=day_into_qtr, y=agg_quarterly_return)) +geom_line(aes(group = 1))
agg_qtrly + facet_wrap(~qtr)+xlab('Day of Quarter')+ylab('Daily Return')+ggtitle('Daily Returns by Quarter, All Coins Aggregated')

```

```{r}
#Making a day for table output in Shiny, quarter max and min days
q_tbl = quarterly_tbl %>% group_by(Name) %>% summarise(max=max(qtr_ret_mean), min = min(qtr_ret_mean))
q_tbl
q_wip = left_join(quarterly_tbl,q_tbl, on='Name')
q_wip$q_max = q_wip$qtr_ret_mean==q_wip$max
q_wip$q_min = q_wip$qtr_ret_mean==q_wip$min
qtr_fin = q_wip %>% dplyr::select(Name, day_into_qtr, qtr_ret_mean, q_max, q_min) %>% filter(q_max==T | q_min==T)
qtr_fin
```

```{r}
#Year calendar transformations--getting the first day of the year and subtracting the date to get the day of the year. Then summarizing the year info by coin and aggregated totals
norm_df
norm_df$first_yr_day = paste0(norm_df$yr,'-01-01')
norm_df$day_into_yr = as.Date(norm_df$date_time) - as.Date(norm_df$first_yr_day) +1

yr_tbl = norm_df %>% group_by(Name, day_into_yr) %>% summarise(yr_ret=mean(day_ret))
yr_tbl
na.omit(yr_tbl)
yr_tbl
# library(reshape2)
# melted_yr = melt(norm_yr_tbl,id.vars=c('day_into_yr','Name') ,measure.vars='norm_yr')
# melted_yr
all_Names_yearly <- ggplot(yr_tbl,aes(x=day_into_yr, y=yr_ret, group=Name)) + geom_line(aes(colour=Name))+xlab('Day of Year')+ylab('Daily Reutrns')+ggtitle('Daily Returns by Day of Year by Coin')
all_Names_yearly

# melted_yr %>% group_by(Name) %>% top_n(1,value)

ttl_by_yr = yr_tbl %>% group_by(day_into_yr) %>% summarise(agg_yearly_return = mean(yr_ret, na.rm=T))
ttl_by_yr
agg_yrly <- ggplot(data = ttl_by_yr, aes(x=day_into_yr, y=agg_yearly_return)) +geom_line(aes(group = 1))+xlab('Day of Year')+ylab('Daily Reutrns')+ggtitle('Daily Returns by Day of Year Aggregated Coins')
agg_yrly
```

```{r}
#Max and min tables for output in shiny
yr_wip = yr_tbl %>% group_by(Name) %>% summarise(max =max(yr_ret), min = min(yr_ret))

yr_wip2 = left_join(yr_tbl, yr_wip, by='Name')
yr_wip2$max_day_y = yr_wip2$max == yr_wip2$yr_ret
yr_wip2$min_day_y = yr_wip2$min == yr_wip2$yr_ret

yr_fin = yr_wip2 %>% dplyr::select(Name, day_into_yr, yr_ret, max_day_y, min_day_y)%>%filter(max_day_y==T | min_day_y==T)

yr_fin
```

```{r}
library(heatmaply)
library(dplyr)
library(tidyr)
#Dropping in the NYSE and Nasdaq info for correlation table, doing some conversion to get there
nasdaq = read_csv('./NASDAQ.csv')
nyse = read_csv('./NYSE.csv')
nasdaq
nasdaq$nasdaq_day_ret = nasdaq$Close / nasdaq$Open - 1
nyse$nyse_day_ret = nasdaq$Close / nasdaq$Open - 1
nyse$Name = 'NYSE'
nasdaq$Name = "NASDAQ"
nyse_tbl = nyse %>% dplyr::select(Name, Date, nyse_day_ret)
nasdaq_tbl = nasdaq %>% dplyr::select(Name, Date, nasdaq_day_ret)
nyse_tbl = nyse_tbl %>% rename(date_time = Date, day_ret = nyse_day_ret)
nyse_tbl
nasdaq_tbl = nasdaq_tbl %>% rename(date_time = Date, day_ret = nasdaq_day_ret)
nasdaq_tbl
norm_df

#Binding rows into the original coin DF
norm_df = bind_rows(norm_df,nyse_tbl)
norm_df = bind_rows(norm_df,nasdaq_tbl)
norm_df

#Making a correlation matrix and then a correlation plot on that matrix
new_df = norm_df %>% dplyr::select(date_time, Name, day_ret)
new_df
new_mat = pivot_wider(new_df, names_from = 'Name', values_from = 'day_ret')
new_mat$date_time = as.numeric(new_mat$date_time)
new_mat
corr_mat = cor(new_mat, use="pairwise.complete.obs")
corrplot(corr_mat, method='circle', type='lower',tl.cex = .6,order='alphabet')


```

```{r}
#Table outputs for Shiny with Hi by day of mo/qtr/yr
norm_df
hi_in_mo = norm_df %>% group_by(Name, yr, mo) %>% summarise(highest_day_mo=max(day_ret),lowest_day_mo = min(day_ret))

hi_in_qtr = norm_df %>% group_by(Name, yr, qtr) %>% summarise(highest_day_qtr=max(day_ret),lowest_day_qtr = min(day_ret))

hi_in_yr = norm_df %>% group_by(Name, yr) %>% summarise(highest_day_yr=max(day_ret),lowest_day_yr = min(day_ret))


```
```{r}
# start_heatmap <- select(norm_df, Name, date_time, day_ret)
# start_heatmap$day_ret = as.numeric(start_heatmap$day_ret)
# start_heatmap
# corr_data = pivot_wider(start_heatmap,id_cols='Name', names_from='date_time', values_from='day_ret')
# corr_data
# cov(x=corr_data)
# ?cor
# library(corrr)
# ?spread
# correlate(corr_data)
# cor(x=corr_data$Aave,y=corr_data$Cardano)
# 
# norm_df %>% group_by(Name, yr) %>% summarise(mean_daily_by_year = mean(yr_ret_mean))

```

```{r}
coins

```
